import { FormEvent, useEffect, useState } from "react";
import { Link, useRouterState } from "@tanstack/react-router";
import { Logo } from "./brand";
import { images, programCategories, type Program } from "@/lib/pdlc-data";
import { usePdlc } from "@/lib/pdlc-store";

const nav = [["Home", "/"], ["About", "/about"], ["Programs", "/programs"], ["Achievers", "/achievers"], ["Faculty", "/faculty"], ["Centers", "/centers"], ["Contact", "/contact"]] as const;

export function PublicShell({ children }: { children: React.ReactNode }) {
  const path = useRouterState({ select: (s) => s.location.pathname });
  const isHome = path === "/"; const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const update = () => setScrolled(window.scrollY > 30); update(); window.addEventListener("scroll", update); return () => window.removeEventListener("scroll", update); }, []);
  if (path.startsWith("/admin")) return <>{children}</>;
  return <div className="site-shell">
    <header className={`site-header ${isHome && !scrolled ? "site-header-overlay" : "site-header-solid"}`}>
      <div className="site-nav"><Logo inverse={isHome && !scrolled} /><nav className="desktop-nav" aria-label="Primary">{nav.map(([label, to]) => <Link key={to} to={to} activeProps={{ className: "active" }}>{label}</Link>)}</nav><Link to="/enquiry" className="btn btn-gold desktop-enquire">Enquire Now <span>↗</span></Link><button className="menu-button" aria-label="Toggle menu" onClick={() => setOpen(!open)}><span/><span/><span/></button></div>
      {open && <nav className="mobile-nav" aria-label="Mobile">{nav.map(([label, to]) => <Link key={to} to={to} onClick={() => setOpen(false)}>{label}<span>↗</span></Link>)}<Link to="/enquiry" className="btn btn-gold" onClick={() => setOpen(false)}>Enquire Now</Link></nav>}
    </header>{children}<Footer /><div className="mobile-actions"><a href="tel:+910000000000">Call</a><Link to="/enquiry">Enquire</Link></div>
  </div>;
}

export function Footer() { const { settings } = usePdlc(); return <footer className="footer"><div className="footer-grid"><div><Logo inverse/><p>{settings.footer}</p><strong>“{settings.tagline}”</strong></div><FooterLinks title="Company" items={[["About", "/about"], ["Faculty", "/faculty"], ["Achievers", "/achievers"], ["Careers", "/careers"]]}/><FooterLinks title="Programs" items={[["CA", "/programs"], ["CFA", "/programs"], ["ACCA", "/programs"], ["CS", "/programs"], ["Commerce", "/programs"]]}/><FooterLinks title="Support" items={[["FAQ", "/faq"], ["Contact", "/contact"], ["Enquiry", "/enquiry"]]}/><div><h3>Contact</h3><p>{settings.address}</p><p>{settings.phone}</p><p>{settings.email}</p><div className="socials"><span>in</span><span>ig</span><span>f</span></div></div></div><div className="footer-bottom"><span>© 2026 PDLC. All rights reserved.</span><span>Demo website · All names and locations are illustrative</span><Link to="/admin/login">Admin Login</Link></div></footer> }
function FooterLinks({ title, items }: { title: string; items: readonly (readonly [string,string])[] }) { return <div><h3>{title}</h3>{items.map(([label,to]) => <Link key={label} to={to}>{label}</Link>)}</div> }

export function PageHero({ eyebrow, title, copy, image = images.classroomImage }: { eyebrow: string; title: string; copy: string; image?: string }) { return <section className="page-hero"><img src={image} alt="PDLC learning experience" width={1408} height={1008}/><div/><div className="page-hero-content"><span className="eyebrow light">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div></section> }
export function SectionTitle({ eyebrow, title, copy, center = false }: { eyebrow: string; title: string; copy?: string; center?: boolean }) { return <div className={`section-title ${center ? "center" : ""}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div> }

export function HomePage() {
 const { programs, achievers, faculty, testimonials, centers, statistics } = usePdlc(); const [testimonial, setTestimonial] = useState(0); const activeTestimonials = testimonials.filter(t=>t.active);
 return <main>
  <section className="home-hero"><img src={images.heroImage} alt="Faculty guiding students in a modern PDLC classroom" width={1920} height={1088}/><div className="hero-overlay"/><div className="hero-content"><span className="eyebrow light">Shape your future with confidence</span><h1>Where Ambition Meets <em>The Right Guidance</em></h1><p>Build strong concepts, sharpen your skills and prepare for professional success with structured learning and expert mentorship.</p><div className="button-row"><Link to="/programs" className="btn btn-gold">Explore Programs <span>↗</span></Link><Link to="/enquiry" className="btn btn-ghost">Book a Counselling Session</Link></div></div><div className="hero-facts"><div><strong>10K+</strong><span>Students Guided</span></div><div><strong>95%</strong><span>Satisfaction</span></div><div><strong>25+</strong><span>Expert Mentors</span></div><div><strong>12+</strong><span>Learning Programs</span></div></div></section>
  <section className="stats-strip">{statistics.map(s=><div key={s.id}><strong>{s.value}</strong><span>{s.label}</span></div>)}</section>
  <section className="section split"><div className="image-composition"><img src={images.mentorshipImage} alt="Academic mentorship at PDLC" width={1408} height={1008} loading="lazy"/><span>Every student<br/><strong>seen & supported</strong></span></div><div><SectionTitle eyebrow="The PDLC approach" title="Education Designed Around Your Success" copy="We bring concept clarity, expert teaching and personal attention into one structured learning journey."/><FeatureList/><Link to="/about" className="text-link">Discover Our Story <span>→</span></Link></div></section>
  <WhyChoose/>
  <section className="section"><SectionTitle eyebrow="Find your path" title="Explore Our Programs" copy="Choose the learning path that matches your ambition."/><ProgramGrid programs={programs.filter(p=>p.active).slice(0,6)}/><div className="center-action"><Link to="/programs" className="btn btn-navy">View All Programs <span>→</span></Link></div></section>
  <section className="featured"><img src={images.classroomImage} alt="Professional excellence classroom" width={1408} height={1008} loading="lazy"/><div className="featured-copy"><span className="eyebrow light">Featured pathway</span><h2>Professional Excellence Program</h2><p>Structured preparation designed to transform ambitious students into confident professionals.</p><FeatureList/><Link to="/programs" className="btn btn-gold">Explore Program</Link></div></section>
  <section className="section"><SectionTitle eyebrow="Wall of fame" title="Our Achievers" copy="Celebrating dedication, discipline and academic excellence."/><PeopleGrid people={achievers.filter(a=>a.active).slice(0,4)} type="achiever"/><div className="center-action"><Link to="/achievers" className="text-link">View All Achievers <span>→</span></Link></div></section>
  <section className="section muted-band"><SectionTitle eyebrow="Learn from the best" title="Meet Our Mentors"/><PeopleGrid people={faculty.filter(f=>f.active)} type="faculty"/></section>
  <Timeline/>
  {activeTestimonials.length > 0 && <section className="testimonial-band"><div><SectionTitle eyebrow="Student voices" title="What Our Students Say"/><div className="testimonial-controls"><button onClick={()=>setTestimonial((testimonial-1+activeTestimonials.length)%activeTestimonials.length)} aria-label="Previous testimonial">←</button><span>{String(testimonial+1).padStart(2,"0")} / {String(activeTestimonials.length).padStart(2,"0")}</span><button onClick={()=>setTestimonial((testimonial+1)%activeTestimonials.length)} aria-label="Next testimonial">→</button></div></div><blockquote><div className="stars">{"★".repeat(activeTestimonials[testimonial]?.rating ?? 5)}</div><p>“{activeTestimonials[testimonial]?.quote}”</p><footer><strong>{activeTestimonials[testimonial]?.name}</strong><span>{activeTestimonials[testimonial]?.program}</span></footer></blockquote></section>}
  <section className="section"><SectionTitle eyebrow="Learn near you" title="Find Your Learning Center" copy="Demo locations shown for presentation only."/><CenterGrid centers={centers.filter(c=>c.active).slice(0,3)}/></section><AdmissionCta/>
 </main>
}

function FeatureList(){return <ul className="feature-list">{["Expert Faculty","Personal Mentorship","Structured Curriculum","Regular Assessments","Career Guidance","Modern Learning Environment"].map(x=><li key={x}><span>✓</span>{x}</li>)}</ul>}
function WhyChoose(){const items=[["01","Expert Faculty","Learn with specialists who make demanding concepts clear."],["02","Personal Mentorship","Receive thoughtful reviews aligned to your goals."],["03","Concept-Based Learning","Understand the why before mastering the how."],["04","Regular Testing","Turn every assessment into a focused improvement plan."],["05","Career Guidance","Connect academic decisions with professional possibilities."],["06","Modern Environment","Study in spaces designed for focus and collaboration."]];return <section className="section navy-band"><SectionTitle eyebrow="The difference" title="Why Students Choose PDLC" center/><div className="reasons-grid">{items.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><i>↗</i></article>)}</div></section>}
export function ProgramGrid({ programs }: { programs: Program[] }) { return <div className="program-grid">{programs.map(p=><article className="program-card" key={p.id}><div className="card-image"><img src={p.image} alt={p.name} width={1408} height={1008} loading="lazy"/><span>{p.category}</span></div><div className="card-body"><h3>{p.name}</h3><p>{p.description}</p><div className="program-meta"><span><small>Duration</small>{p.duration}</span><span><small>Format</small>{p.format}</span></div><ul>{p.features.map(f=><li key={f}>✓ {f}</li>)}</ul><div className="card-actions"><Link to="/programs/$programId" params={{ programId:p.id }} className="text-link">View Details →</Link><Link to="/enquiry" className="btn btn-small">Enquire</Link></div></div></article>)}</div> }
export function ProgramsPage(){const {programs}=usePdlc(); const [filter,setFilter]=useState("All"); const filtered=programs.filter(p=>p.active&&(filter==="All"||p.category===filter));return <main><PageHero eyebrow="Programs" title="Build expertise that moves you forward." copy="Explore structured pathways shaped for professional confidence, exam readiness and long-term growth."/><section className="section"><div className="filter-row">{programCategories.map(c=><button className={filter===c?"selected":""} key={c} onClick={()=>setFilter(c)}>{c}</button>)}</div><ProgramGrid programs={filtered}/>{!filtered.length&&<div className="empty">No active programs in this category.</div>}</section><AdmissionCta/></main>}
export function ProgramDetails({ program }: { program?: Program }){const {notify}=usePdlc();if(!program)return <main><PageHero eyebrow="Programs" title="Program not found" copy="This demo program may have been removed in the current session."/><section className="section"><Link to="/programs" className="btn btn-navy">Back to Programs</Link></section></main>;return <main><PageHero eyebrow={program.category} title={program.name} copy={program.description} image={program.image}/><section className="section detail-grid"><div><SectionTitle eyebrow="Program overview" title="A clear plan for confident progress" copy={`Designed for ${program.eligibility}, this ${program.duration} pathway combines guided learning, practice and personal review.`}/><h3>Course structure</h3><div className="module-grid">{program.modules.map((m,i)=><div key={m}><span>0{i+1}</span><strong>{m}</strong><p>Concept lessons, practice workshops and progress checks.</p></div>)}</div><h3>Learning outcomes</h3><FeatureList/><h3>Program FAQs</h3><FaqList limit={3}/></div><aside className="detail-aside"><span>Program snapshot</span><dl><dt>Duration</dt><dd>{program.duration}</dd><dt>Eligibility</dt><dd>{program.eligibility}</dd><dt>Learning format</dt><dd>{program.format}</dd><dt>Support</dt><dd>Mock tests + mentorship</dd></dl><Link to="/enquiry" className="btn btn-gold">Enquire Now</Link><button className="btn btn-outline" onClick={()=>notify("Demo brochure request noted")}>Download Brochure</button></aside></section></main>}
export function PeopleGrid({people,type}:{people:ReturnType<typeof usePdlc>["faculty"];type:"faculty"|"achiever"}){return <div className="people-grid">{people.map(p=><article key={p.id}><img src={p.image} alt={p.name} width={1408} height={1008} loading="lazy"/><div><span>{p.program}</span><h3>{p.name}</h3><p>{p.bio||`${p.detail} · ${p.meta}`}</p><strong>{type==="faculty"?`${p.detail} · ${p.meta}`:p.detail}</strong></div></article>)}</div>}
export function CenterGrid({centers}:{centers:ReturnType<typeof usePdlc>["centers"]}){const {notify}=usePdlc();return <div className="center-grid">{centers.map(c=><article key={c.id}><img src={c.image} alt={`${c.name} demo center`} width={1408} height={1008} loading="lazy"/><div><span>Demo location</span><h3>{c.name}</h3><p>{c.address}</p><p>{c.hours}</p><strong>{c.programs}</strong><div className="card-actions"><button className="text-link" onClick={()=>notify(`${c.name} demo details opened`)}>View Center</button><button className="text-link" onClick={()=>notify("Directions are disabled in this frontend demo")}>Get Directions ↗</button></div></div></article>)}</div>}
function Timeline(){return <section className="section timeline"><SectionTitle eyebrow="The learning experience" title="A rhythm designed for progress" center/><div>{[["01","Learn","Build strong fundamentals."],["02","Practice","Solve structured problems."],["03","Analyse","Track performance."],["04","Improve","Work with mentors."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>}
export function AdmissionCta(){return <section className="admission"><span className="eyebrow light">Start a conversation</span><h2>Your Future Deserves The Right Direction</h2><p>Speak with our academic counsellors and discover the right program for your goals.</p><div className="button-row"><Link to="/contact" className="btn btn-ghost">Talk To A Counsellor</Link><Link to="/enquiry" className="btn btn-gold">Enquire Now</Link></div></section>}
export function FaqList({limit}:{limit?:number}){const {faqs}=usePdlc();const [open,setOpen]=useState<string|null>(null);return <div className="faq-list">{faqs.filter(f=>f.active).slice(0,limit).map(f=><article className={open===f.id?"open":""} key={f.id}><button onClick={()=>setOpen(open===f.id?null:f.id)}><span>{f.question}</span><i>{open===f.id?"−":"+"}</i></button>{open===f.id&&<p>{f.answer}</p>}</article>)}</div>}
export function EnquiryForm({career}: {career?: string}){const {programs,centers,setEnquiries,notify}=usePdlc();const [success,setSuccess]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);if(!career)setEnquiries(v=>[{id:`e${Date.now()}`,name:String(data.get("name")),email:String(data.get("email")),phone:String(data.get("phone")),program:String(data.get("program")),center:String(data.get("center")),date:"26 Sep 2026",status:"New"},...v]);setSuccess(true);e.currentTarget.reset();}return <><form className="form-grid" onSubmit={submit}><label>Full Name<input name="name" required placeholder="Your full name"/></label><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Phone Number<input name="phone" required placeholder="+91"/></label>{career?<label>Position<input value={career} readOnly/></label>:<><label>Interested Program<select name="program" required><option value="">Select program</option>{programs.filter(p=>p.active).map(p=><option key={p.id}>{p.name}</option>)}</select></label><label>Preferred Center<select name="center" required><option value="">Select center</option>{centers.filter(c=>c.active).map(c=><option key={c.id}>{c.name}</option>)}</select></label></>}<label className="full">Message<textarea name="message" rows={4} placeholder="Tell us about your goals"/></label><button className="btn btn-gold full" type="submit">{career?"Submit Application":"Submit Enquiry"}</button></form>{success&&<div className="modal-backdrop"><div className="success-modal"><button aria-label="Close" onClick={()=>setSuccess(false)}>×</button><span>✓</span><h2>Thank You!</h2><p>{career?"Your application has been recorded for this demo.":"Your enquiry has been recorded for this demo."}</p><button className="btn btn-navy" onClick={()=>{setSuccess(false);notify("Demo submission completed")}}>Done</button></div></div>}</>}