/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchieversRouteImport } from './routes/achievers'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CentersRouteImport } from './routes/centers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchieversRoute = AchieversRouteImport.update({
  id: '/achievers',
  path: '/achievers',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersRoute = CentersRouteImport.update({
  id: '/centers',
  path: '/centers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => ProgramsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievers': typeof AchieversRoute
  '/careers': typeof CareersRoute
  '/centers': typeof CentersRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievers': typeof AchieversRoute
  '/careers': typeof CareersRoute
  '/centers': typeof CentersRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievers': typeof AchieversRoute
  '/careers': typeof CareersRoute
  '/centers': typeof CentersRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievers'
    | '/careers'
    | '/centers'
    | '/contact'
    | '/enquiry'
    | '/faculty'
    | '/faq'
    | '/programs'
    | '/testimonials'
    | '/admin/dashboard'
    | '/admin/login'
    | '/programs/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievers'
    | '/careers'
    | '/centers'
    | '/contact'
    | '/enquiry'
    | '/faculty'
    | '/faq'
    | '/programs'
    | '/testimonials'
    | '/admin/dashboard'
    | '/admin/login'
    | '/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievers'
    | '/careers'
    | '/centers'
    | '/contact'
    | '/enquiry'
    | '/faculty'
    | '/faq'
    | '/programs'
    | '/testimonials'
    | '/admin/dashboard'
    | '/admin/login'
    | '/programs/$programId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchieversRoute: typeof AchieversRoute
  CareersRoute: typeof CareersRoute
  CentersRoute: typeof CentersRoute
  ContactRoute: typeof ContactRoute
  EnquiryRoute: typeof EnquiryRoute
  FacultyRoute: typeof FacultyRoute
  FaqRoute: typeof FaqRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievers': {
      id: '/achievers'
      path: '/achievers'
      fullPath: '/achievers'
      preLoaderRoute: typeof AchieversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers': {
      id: '/centers'
      path: '/centers'
      fullPath: '/centers'
      preLoaderRoute: typeof CentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchieversRoute: AchieversRoute,
  CareersRoute: CareersRoute,
  CentersRoute: CentersRoute,
  ContactRoute: ContactRoute,
  EnquiryRoute: EnquiryRoute,
  FacultyRoute: FacultyRoute,
  FaqRoute: FaqRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
